### ISSUE TITLE
[FIX] 인맥 리스트 수정

### ISSUE THREAD

**Issue by seunggyun-jeong** [DeveloperAcademy-POSTECH/MC3-Team3-GrayMa#124]
## 🟣 Todo
- [ ]  배경색 수정
- [ ]  List Row (피그마와 똑같이 수정)
    - [ ]  캐릭터 초상화
    - [ ]  글자 폰트 수정
    - [ ]  강점태그 보이도록
- [ ]  리스트 전체 네비게이션 연결
- [ ]  인맥 추가 +아이콘 사이즈 조정
- [ ]  필터 이미지 테두리 수정
- [ ]  삭제 경고 문구 표시
