### ISSUE TITLE
[FEAT] 강점 추가뷰 수정

### ISSUE THREAD

**Issue by kdb1217** [DeveloperAcademy-POSTECH/MC3-Team3-GrayMa#125]
## 🟣 Todo
- 강점 추가 - 래쉬
    - [ ]  미입력 시 x버튼 제거
    - [ ]  직접 추가하기 태그화
    - [ ]  이미 존재하는 강점 선택 시 키보드 Hide 및 강점 태그화
    - [ ]  강점 리스트 테두리(Stroke) 수정
    - [ ]  강점 이어 추가하기 기능 (후순위)
