### ISSUE TITLE
[FEAT] 강점메인뷰 수정

### ISSUE THREAD

**Issue by kdb1217** [DeveloperAcademy-POSTECH/MC3-Team3-GrayMa#127]
## 🟣 Todo
- [x]  강점 리스트 전체 터치 시 디테일 뷰로 이동
- [x]  강점 삭제 시 안내 메세지 버튼 색 변경
- [x]  이미지 포함하여 전체적으로 스크롤 될 수 있도록 수정
- [ ]  강점 시각화에 보여지는 강점 갯수 제한 3개
- [ ]  강점 시각화 애니메이션……
