### ISSUE TITLE
[FIX] 전체 짜잘한 기능 수정

### ISSUE THREAD

**Issue by seunggyun-jeong** [DeveloperAcademy-POSTECH/MC3-Team3-GrayMa#158]
## 🟣 Todo
- [x]  노트 최신순 정렬
- [x]  메타볼 3개로 제한
    - [x]  강점 레벨 순
    - [x]  노트 기록 순
- [x]  강점을 노트 최신 순 정렬
- [x]  강점 추가 뷰
- [x]  동일 강점 인맥 띄우기
- [x]  다크모드 비활성화
- [x]  가로모드 비활성화
